# Dosya Adı: render.yaml

services:
  - type: web
    name: hospitalproject53
    env: docker
    buildCommand: "./mvnw clean install"
    dockerfilePath: Dockerfile
    envVars:
      - key: PROFILE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-ctqno652ng1s73ecmnjg-a/hospitalpostgresql
      - key: SPRING_DATASOURCE_USERNAME
        value: hospitalpostgresql_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: Ex42FbEKM83jniUX7ABdqcTs4p739UxL
