name: Deploy Backend
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Clear GitHub Actions Cache
      run: |
        sudo rm -rf /home/runner/work/_actions
        
    - name: Test Secrets Access
      run: echo "Secrets Erişimi Test Ediliyor"
      env:
        PASSWORD: ${{ secrets.SERVER_PASSWORD }}
    


    # Maven Build İşlemi
    - name: Build Backend
      run: mvn clean package

    # JAR Dosyasını Sunucuya Gönder
    - name: Transfer Backend
      run: |
        expect << EOF
        spawn scp target/hospital-management-0.0.1-SNAPSHOT.jar root@37.148.209.189:/home/ubuntu/
        expect "password:"
        send "${{ secrets.SERVER_PASSWORD }}\r"
        expect eof
        EOF
              
    # Sunucuda JAR Dosyasını Çalıştır
    - name: Start Backend on Server
      run: |
        expect << EOF
        spawn ssh root@37.148.209.189
        expect "password:"
        send "${{ secrets.SERVER_PASSWORD }}\r"
        expect "$ "
        send "nohup java -jar /home/ubuntu/hospital-management-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod > app.log 2>&1 &\r"
        expect "$ "
        send "exit\r"
        expect eof
        EOF
