name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Kodları Checkout Et
    - name: Checkout Code
      uses: actions/checkout@v2

    # Java Kurulumu
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    # Maven Build İşlemi
    - name: Build Backend
      run: mvn clean package

    # JAR Dosyasını Sunucuya Gönder
    - name: Transfer Backend
      run: |
        expect << EOF
        spawn scp target/hospital-management-0.0.1-SNAPSHOT.jar root@37.148.209.189:/home/ubuntu/
        expect "password:"
        send "${{ secrets.SERVER_PASSWORD }}\r"
        expect eof
        EOF

    # Sunucuda JAR Dosyasını Çalıştır
    - name: Start Backend on Server
      run: |
        expect << EOF
        spawn ssh root@37.148.209.189
        expect "password:"
        send "${{ secrets.SERVER_PASSWORD }}\r"
        expect "$ "
        send "nohup java -jar /home/ubuntu/hospital-management-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod > app.log 2>&1 &\r"
        expect "$ "
        send "exit\r"
        expect eof
        EOF
