name: Deploy Backend
 
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Kodları Checkout Et
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    # SSH için fingerprint doğrulama
    - name: Add SSH Host Key to Known Hosts
      run: |
        ssh-keyscan -H 37.148.209.189 >> ~/.ssh/known_hosts

    # Gereksiz Cache Temizliği Yerine Daha Spesifik İşlem
    - name: Clear Specific GitHub Actions Cache
      run: |
        sudo rm -rf /home/runner/work/_actions/specific-folder  # Spesifik bir klasör temizlenmeli

    # Secrets Erişimini Test Et
    - name: Test Secrets Access
      run: echo "Secrets Erişimi Test Ediliyor"
      env:
        PASSWORD: ${{ secrets.SERVER_PASSWORD }}

    # Maven Build İşlemi
    - name: Build Backend
      run: mvn clean package

    # Expect Paketini Yükle
    - name: Install Expect
      run: sudo apt-get update && sudo apt-get install -y expect

    # JAR Dosyasını Sunucuya Gönder
    - name: Transfer Backend
      run: |
       expect << EOF
       spawn scp target/hospital-management-0.0.1-SNAPSHOT.jar root@37.148.209.189:/home/ubuntu/
       expect {
         "Are you sure you want to continue connecting" { send "yes\r"; exp_continue }
         "password:" { send "${{ secrets.SERVER_PASSWORD }}\r" }
       }
       expect eof
       EOF

    - name: Start Backend on Server
      run: |
       expect << EOF
       spawn ssh root@37.148.209.189
       expect {
         "Are you sure you want to continue connecting" { send "yes\r"; exp_continue }
         "password:" { send "${{ secrets.SERVER_PASSWORD }}\r" }
       }
       expect "$ "
       send "nohup java -jar /home/ubuntu/hospital-management-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod > app.log 2>&1 &\r"
       expect "$ "
       send "exit\r"
       expect eof
       EOF
